/**
 * Do not edit directly
 * Generated on Sun, 11 Aug 2019 05:31:39 GMT
 */

export const ColorGray = "#6a737d";
export const ColorRed = "#bf0201";
export const ColorBlue = "#0070d2";
export const ColorOrange = "#f66a0a";
export const ColorYellow = "#ffd33d";
export const ColorGreen = "#28a745";
export const ColorBlack = "#000000";
export const ColorWhite = "#ffffff";
export const ColorDark10 = "#000000"; // lightens
export const ColorDark25 = "#707070"; // highlight text
export const ColorDark50 = "#2a2a2a"; // default text
export const ColorDark100 = "#232323"; // Element background etc
export const ComponentBtnPadding = "1.25rem";
export const ComponentBtnFontSize = "1.07rem";
export const ComponentBtnBackgroundColor = "#232323";
export const ComponentBtnColor = "transparentize(#6a737d, .25)";
export const ComponentBtnHoverColor = "darken(transparentize(#6a737d, .25), 10%)";
export const ComponentBtnHoverBackgroundColor = "darken(#232323, 10%)";
export const ComponentBtnBlueBackgroundColor = "#0070d2";
export const ComponentBtnCursor = "pointer";
export const ComponentBtnBorder = "none";
export const ComponentBtnBorderRadius = "9999rem";
export const ComponentSwatchMinHeight = "60rem";
export const ComponentSwatchWidth = "100rem";
export const FontSizeBase = "1rem"; // descriptions...
export const FontSizeFinePrint = "0.75rem"; // descriptions...
export const FontSizeNotes = "0.875rem"; // descriptions...
export const FontSizeShortCopy = "1.3rem"; // descriptions...
export const FontSizeLead = "1.5rem"; // descriptions...
export const FontSizeSubtitles = "1.75rem"; // descriptions...
export const FontSizeTitleBase = "2rem"; // descriptions...
export const FontSizeTitleXs = "2.5rem"; // descriptions...
export const FontSizeTitleSm = "3rem"; // descriptions...
export const FontSizeTitleMd = "3.5rem"; // descriptions...
export const FontSizeTitleLg = "4rem"; // descriptions...
export const FontSizeTitleXl = "5rem"; // descriptions...
export const FontWeightMedium = "500"; // descriptions...
export const FontWeightBold = "700"; // descriptions...